### ISSUE TITLE
Failed to delete project

### ISSUE THREAD

**Issue by hwshim** [webida/webida-server#135] opened 2015-11-10 08:09 UTC
![image](https://cloud.githubusercontent.com/assets/7447396/11057389/dc5855e8-87cd-11e5-8555-77642b1b35a0.png)

![image](https://cloud.githubusercontent.com/assets/7447396/11057368/b5f3fd30-87cd-11e5-958d-fbd39a260dc1.png)

**Comment by gotchazipc** [comment] 2015-11-20 06:41
cannot reproduce problem. seems to be fixed with recent commits.

**Closed by gotchazipc** 2015-11-20 06:41 UTC
Labels: bug
