### ISSUE TITLE
Internal Server Error while authorizing

### ISSUE THREAD

**Issue by hwshim** [webida/webida-server#73] opened 2015-08-17 03:32 UTC
Sometimes I met the following error message.

[webida-0.3.js:332]

GET https://auth.webida.net/webida/api/oauth/authorize?response_type=token&redirect_uri=https%3A%2F%2Fwebida.net%2Fauth.html&client_id=***************
500 (Internal Server Error)

mod.TokenGenerator.generateNewToken @ webida-0.3.js?1439781474169:332ensureAuthorize @ webida-0.3.js?1439781474169:343FileSystem.exists @ webida-0.3.js?1439781474169:1342init @ app.js?1439781474169:259(anonymous function) @ app.js?1439781474169:211mod.AuthService.initAuth @ webida-0.3.js?1439781474169:384proceed @ app.js?1439781474169:210startup @ app.js?1439781474169:224(anonymous function) @ index.html?workspace=e18afer_A/test:31ha @ dojo.js.uncompressed.js:1104(anonymous function) @ dojo.js.uncompressed.js:1267ia @ dojo.js.uncompressed.js:1247fa @ dojo.js.uncompressed.js:1262d @ dojo.js.uncompressed.js:1317f @ dojo.js.uncompressed.js:12355d @ dojo.js.uncompressed.js:12378

**Comment by cimfalab** [comment] 2015-08-17 03:40
Is this related with #72 ? (postMessage problem)

**Comment by kyungmi** [comment] 2015-08-17 05:00
@cimfalab There is no relation between this issue and #72.

**Comment by kyungmi** [comment] 2015-08-17 08:28
@hwshim Which page did you experience this issue on?

**Comment by kyungmi** [comment] 2015-08-18 03:34
I think it is caused by `EMFILE error` occurred by `file-session-store` of auth server. The `file-session-store` has been replaced with `connect-sqlite3` now. 
So I'm going to close this issue. 
Notice me when the same error is occurred again.

**Closed by kyungmi** 2015-08-18 03:34 UTC
Labels: critical

**Comment by sangjin3** [comment] 2015-08-18 03:40
When or where the "EMFILE error" occur?

**Comment by kyungmi** [comment] 2015-08-18 05:59
@sangjin3 `file-session-store` runs deleting all expired session files (about 140,000 files was in the sessions directory) every 1 hour. 
If auth server try to read a session file to check token's validity at this time, the 'EMFILE(too many open files)' error is occurred.

**Comment by sangjin3** [comment] 2015-08-18 06:13
@kyungmi session-file-store adopted the bagpipe modules to avoid EMFILE error. 
So it fixed after 0.0.13 version.
It seems better upgrading just session-file-store module's version.

**Comment by kyungmi** [comment] 2015-08-18 06:18
@sangjin3 Thanks for the information. But it is very abnormal case that about 140,000 files are in 'a' directory.
So I think `connect-sqlite3` is more safe choice before we take another option.
